import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'react-hot-toast';
import api from '../services/api';
import Logo from '../components/Logo';
import { useAuth } from '../context/AuthContext';

interface VerifyResponse {
    message: string;
}

interface ApiError {
    response?: {
        status: number;
        data: {
            message: string;
        };
    };
    message: string;
}

const VerifyEmail: React.FC = () => {
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();
    const { user, getUser } = useAuth();
    
    const verifyUrl = searchParams.get('verify_url');
    
    const [status, setStatus] = useState<'loading' | 'success' | 'error'>('loading');
    const [errorMessage, setErrorMessage] = useState<string>('');

    useEffect(() => {
        const verifyEmail = async () => {
            if (!verifyUrl) {
                setStatus('error');
                setErrorMessage('Invalid verification link.');
                return;
            }

            try {
                // The verifyUrl is a full absolute URL generated by Laravel (including the signature)
                const response = await api.get<VerifyResponse>(verifyUrl);
                
                setStatus('success');
                toast.success(response.data.message || 'Email verified successfully!');
                
                // Refresh the user context so the app knows the email is verified
                await getUser();
                
                // Redirect based on role
                setTimeout(() => {
                    if (user?.role === 'Admin') navigate('/dashboard', { replace: true });
                    else if (user?.role === 'Technician') navigate('/technicien', { replace: true });
                    else navigate('/client', { replace: true });
                }, 2000);
                
            } catch (err) {
                setStatus('error');
                const apiError = err as ApiError;
                setErrorMessage(apiError.response?.data?.message || 'Verification failed or link expired.');
            }
        };

        verifyEmail();
    }, [verifyUrl, navigate, getUser, user?.role]);

    const isDark = document.documentElement.classList.contains('dark');
    const t = {
        pageBg:      isDark ? '#020617' : '#eff6ff',
        text:        isDark ? '#f1f5f9' : '#191c1e',
        textMuted:   isDark ? '#94a3b8' : '#64748b',
    };

    return (
        <div style={{ minHeight: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center', fontFamily: "'Inter', system-ui, sans-serif", backgroundColor: t.pageBg }}>
            <motion.div 
                initial={{ opacity: 0, y: 20 }} 
                animate={{ opacity: 1, y: 0 }} 
                style={{ width: '100%', maxWidth: '400px', padding: '32px', textAlign: 'center' }}
            >
                <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '24px' }}>
                    <Logo variant={isDark ? "dark" : "light"} />
                </div>
                
                <h2 style={{ fontSize: '24px', fontWeight: '800', color: t.text, marginBottom: '16px' }}>
                    Email Verification
                </h2>

                <AnimatePresence mode="wait">
                    {status === 'loading' && (
                        <motion.div
                            key="loading"
                            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px' }}
                        >
                            <span className="material-symbols-outlined animate-spin" style={{ fontSize: '40px', color: '#004ac6' }}>
                                progress_activity
                            </span>
                            <p style={{ color: t.textMuted, margin: 0 }}>Verifying your email address...</p>
                        </motion.div>
                    )}

                    {status === 'success' && (
                        <motion.div
                            key="success"
                            initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
                            style={{ padding: '24px', background: isDark ? 'rgba(16, 185, 129, 0.1)' : '#d1fae5', borderRadius: '16px', border: `1px solid ${isDark ? 'rgba(16, 185, 129, 0.2)' : '#a7f3d0'}` }}
                        >
                            <span className="material-symbols-outlined" style={{ color: '#10b981', fontSize: '48px', marginBottom: '12px' }}>
                                verified
                            </span>
                            <p style={{ color: isDark ? '#34d399' : '#065f46', margin: 0, fontWeight: 600 }}>
                                Thank you! Your email is now verified. Redirecting to your dashboard...
                            </p>
                        </motion.div>
                    )}

                    {status === 'error' && (
                        <motion.div
                            key="error"
                            initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
                            style={{ padding: '24px', background: isDark ? 'rgba(239, 68, 68, 0.1)' : '#fee2e2', borderRadius: '16px', border: `1px solid ${isDark ? 'rgba(239, 68, 68, 0.2)' : '#fecaca'}` }}
                        >
                            <span className="material-symbols-outlined" style={{ color: '#ef4444', fontSize: '48px', marginBottom: '12px' }}>
                                error
                            </span>
                            <p style={{ color: isDark ? '#f87171' : '#991b1b', margin: 0, fontWeight: 600, marginBottom: '16px' }}>
                                {errorMessage}
                            </p>
                            <button 
                                onClick={() => navigate('/login')}
                                style={{ padding: '10px 20px', borderRadius: '8px', border: 'none', background: '#ef4444', color: '#fff', fontWeight: 600, cursor: 'pointer' }}
                            >
                                Return to Login
                            </button>
                        </motion.div>
                    )}
                </AnimatePresence>
            </motion.div>
        </div>
    );
};

export default VerifyEmail;
